<?php

declare(strict_types=1);

namespace BitWasp\Test\Wallet\Console\Command\Db;

use BitWasp\Bitcoin\Chain\Params;
use BitWasp\Bitcoin\Chain\ParamsInterface;
use BitWasp\Bitcoin\Math\Math;
use BitWasp\Wallet\Console\Command\Db\Init;
use BitWasp\Wallet\DbManager;
use BitWasp\Wallet\Params\RegtestParams;
use BitWasp\Wallet\Params\TestnetParams;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;

class InitTest extends TestCase
{
    /**
     * @var CommandTester
     */
    private $commandTester;

    /**
     * @var string
     */
    private $targetDb;

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        $application = new Application();
        $application->add(new Init());
        $command = $application->find('db:init');
        $this->commandTester = new CommandTester($command);
        $this->targetDb = sys_get_temp_dir()."/walletman-unittest-dbinit.sqlite";
        if (file_exists($this->targetDb)) {
            unlink($this->targetDb);
        }
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()/* The :void return type declaration that should be here would cause a BC issue */
    {
        $this->commandTester = null;
        if (file_exists($this->targetDb)) {
            unlink($this->targetDb);
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    private function assertTableExists(\PDO $pdo, string $table)
    {
        $checkTableStmt = $pdo->prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?");
        $checkTableStmt->execute([
            $table,
        ]);
        $result = $checkTableStmt->fetchAll(\PDO::FETCH_ASSOC);
        $this->assertCount(1, $result, "should find table");
        $this->assertEquals($table, $result[0]["name"], "table name should match expected value");
    }

    public function getTestnetFlags(): array
    {
        $math = new Math();
        $mainnet = new Params($math);
        $testnet = new TestnetParams($math);
        $regtest = new RegtestParams($math);

        return [
            [null, $mainnet],
            ["--testnet", $testnet],
            ["-t", $testnet],
            ["--regtest", $regtest],
            ["-r", $regtest],
        ];
    }

    /**
     * @dataProvider getTestnetFlags
     * @param string $flag
     * @param ParamsInterface $params
     */
    public function testInitBitcoinTestnet(?string $flag, ParamsInterface $params)
    {
        $input = [
            'command'  => "db:init",
            'database' => $this->targetDb,
        ];
        if ($flag) {
            $input[$flag] = null;
        }

        $this->assertEquals(0, $this->commandTester->execute($input));

        // the output of the command in the console
        $output = $this->commandTester->getDisplay();
        $this->assertContains('Database setup in', $output);

        $dbMan = new DbManager();
        $db = $dbMan->loadDb($this->targetDb);
        $pdo = $db->getPdo();
        $this->assertTableExists($pdo, "header");
        $this->assertTableExists($pdo, "wallet");
        $this->assertTableExists($pdo, "key");
        $this->assertTableExists($pdo, "script");
        $this->assertTableExists($pdo, "tx");
        $this->assertTableExists($pdo, "utxo");

        $header = $db->getBestHeader();
        $this->assertEquals($params->getGenesisBlockHeader()->getHash()->getHex(), $header->getHash()->getHex());
    }
}
